In [1]:
# Installing numpy for my project
!pip install numpy

  Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)



[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# import numpy for my project
import numpy as np

In [5]:
student_record = np.arange(0,10,1)
student_record

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Convert all odds to -1
new_record = np.array(list(map( lambda x: -1 if  x%2 != 0 else x, student_record)))
new_record


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
# Convert it into a two-dimensional array
new_arr2 = student_record.reshape(2,5)
new_arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
# Sum of all evens ( not events , most likely  typo )
sum = 0
for x in student_record:
    if x % 2 == 0:
     sum += x
print(sum)

20
